server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com #是C:\Windows\System32\drivers\etc\hosts配置的
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/